#  ----------------------------------------------------
#  AutoMessage Configuration File
#  ----------------------------------------------------
#  Message Configuration:
#     Messages are handled in lists to allow for advanced customization!
#     Feel free to add color codes by using & in your messages!
#     To split a message onto multiple lines use the \n delimiter!
#     Lines starting with / will be run as a command!
#     To add single apostrophes into a message use ''.
#     For a complete tutorial go to http://dev.bukkit.org/server-mods/automessage.
#     If you are unfamiliar with YAML use the in-game commands: /am help

settings:
  enabled: true
  min-players: 0
  log-to-console: false
message-lists:
  default:
    enabled: true
    random: false
    interval: 120
    expiry: -1
    prefix: '&r[&4Announcement&r] '
    suffix: '&r[&4Announcement&r]'
    messages:
    - ' &1Your playing on the open beta of legend5140 and matt1965pro's modpack server!'
    - '&3Have a suggestion for the server or modpack? send server suggestions to matt1965pro, send modpack suggestions to legend5140' 
    - '&6Github Repo, &2www.github.com/matt1965pro/modpack/
    - '&dwe REALY need a name for the modpack suggest some stuff to us!'
  vip:
    enabled: false
    random: false
    interval: 45
    expiry: -1
    prefix: '[&bPrefix&r]\n'
    suffix: '\n[&4Suffix&r] '
    messages:
    - 'This message will be displayed only to users with \nautomessage.receive.vip!'